config/routes.rb
Rails.application.routes.draw do

  get 'detail/join'

  resources "lists"

  get "lists/hello_world"
  post "lists/hello_world"

  devise_for :users

  get 'home/index'

  get 'home/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root
  root to: "home#index"

  get 'home#index' => 'home#index'

  get 'lists/' => 'lists#create'

  get 'lists/:id', to: 'lists#show', as: 'event'

  get 'search' => 'search#index'
  get 'search/:title' => 'search#index'
  get 'search/:what' => 'search#index'
  get 'search/:when' => 'search#index'
  get 'search/:where' => 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one :host, foreign_key: "user_id", class_name: "User"
  has_many :guests, foreign_key: "user_id", class_name: "User"

  # 商品名は必須
  validates :title, presence: true
  validates :what, presence: true
  validates :when, presence: true
  validates :where, presence: true

  mount_uploader :image, ImageUploader
end

app/models/organizer.rb
class Organizer < ApplicationRecord
end

app/models/participant.rb
class Participant < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/detail_controller.rb
class DetailController < ApplicationController
  def join
    @event_id = params[:event_id]
    Participant.create(:event_id => params[:event_id] , :user_id => current_user.id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :where, :what, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.joins("INNER JOIN organizers ON organizers.event_id = events.id")
               .joins("INNER JOIN users ON organizers.user_id = users.id")
               .select("events.*, users.name")
               .order(created_at: 'desc')
  end

  def show
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @events = Event.joins("INNER JOIN organizers ON organizers.event_id = events.id")
               .joins("INNER JOIN users ON organizers.user_id = users.id")
               .select("events.*, users.name")
               .order(created_at: 'desc')
  end

  def show
    @event = Event.find(params[:id])
    @attendee = Event
               .where(id: params[:id])
               .joins("INNER JOIN participants ON participants.event_id = events.id")
               .joins("INNER JOIN users ON users.id = participants.user_id")
               .select("users.*")
    @organizer = Event
               .where(id: params[:id])
               .joins("INNER JOIN organizers ON organizers.event_id = events.id")
               .joins("INNER JOIN users ON users.id = organizers.user_id")
               .select("users.*")
               
    gon.place = @event.where
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event created.'
    else
      render :new
    end
  end

  private

  def event_params
    # ubmitしたデータのうち、指定したデータのみpermitの引数に指定
    params.require(:event).permit(
      :title, :when, :where, :what
    )
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    #what = params[:what] || "%"
    #whn = params[:when] || "%"
    #where = params[:where] || "%"
    #@events = Event
    #  .where("events.what LIKE ?", "%#{what}%")
    #  #.where("events.when LIKE ?", "%#{whn}%")
    #  #.where("events.where LIKE ?", "%#{where}%")
    title = params[:title] || ""
    @events = Event.where("events.title LIKE ?", "%#{title}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/detail/join.html.erb
<h1>Detail#join</h1>
<p>Find me in app/views/detail/join.html.erb</p>
<p><%= simple_format @event_id %></p>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :where %>
    <%= form.text_field :where, id: :event_where %>
  </div>

  <div class="field">
    <%= form.label :what %>
    <%= form.text_field :what, id: :event_what %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Where</th>
      <th>What</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.where %></td>
        <td><%= event.what %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Where:</strong>
  <%= @event.where %>
</p>

<p>
  <strong>What:</strong>
  <%= @event.what %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script
  </head>

  <body style="overflow: scroll";>
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>

  <div class="container">
    <% @events.each do |event| %>
    <div class="card" style="width: 20rem; float: left; margin: 30px 8px 20px 8px; border-radius: 2px; padding: 5px";>
      <img class="card-img-top" src="shell-snail-shell-snail-60711.jpeg" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title"><%= event.title %><hr></h4>
        <p class="card-text"><%= event.what %></p>
        <p class="card-text"><%= event.where %></p>
        <p class="card-text"><%= event.when %></p>
        <p class="card-text"><%= event.name %></p>
        <%= link_to "Go somewhere", event_path(event), :class => "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </body>
</html>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <title>Sports</title>
    <%= csrf_meta_tags %>

    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.jpg') %>
  </head>

  <body style="background-color:rgb(172,196,207);" >

  <nav style="font-size: 1.9rem";>
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %> 
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、
          deviseにより自動で作成されてますので、rake routesで確認できます -->
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to "Top", lists_path %> |
        <%= link_to 'Change Profile', edit_user_registration_path %> |
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Top", lists_path %> |
        <%= link_to "Sign in", new_user_registration_path %> |
        <%= link_to "Log in", new_user_session_path %>
      <% end %>
    </nav>
    <br>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="width:800px; margin-left:auto; margin-right:auto;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="index">
    <img src="/assets/images/icon.jpg" width="30" height="30" alt="">
  </a>
  <a class="navbar-brand" href="#">Sport2Me</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Log In</a>
      </li>
    </ul>
  </div>
</nav>

    


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer style="background-color:#ffffff;">
    <address style="text-align:center;">&copy; Copyright 2017. All Rights Reserved.</address>
    </footer>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap Sample</title>
  </head>

  <body>
  <center>

  <form action="/search" method="get">
  Search: <input type="text" name="title">
  <input type="submit" value="Submit">
  </form>
  
  <h2><%= link_to 'Add new event', "lists/new" %></h2>

  <h3>Popular</h3>
  <div class="container">
    <section class="content-gallery scroll-bar" style="background-color:rgb(172,196,207);">
      <% @events.each do |event| %>
      <section class="content-gallery-card">
        <div class="card text-right" style="padding: 10px; margin: 5px;">
          <% if event.image? %>
            <%= image_tag event.image, :class => "card-img-top", :style => "width:120px; height:120px; margin-right:auto; margin-left:auto;"%>
          <% else %>
          <% end %>
          <div class="card-block">
            <h4 class="card-title"><%= event.title %></h4>
            <p class="card-text">W<%= event.what %><br>
            <%= event.where %><br>
            <%= event.when %><br>
            <%= event.name %><br></p>
            <%= link_to "Go somewhere", event_path(event), :class => "btn btn-primary", :style => "text-decoration: none;" %>
          </div>
        </div>
        </section>
      <% end %>
    </section>
  </div>
  </center>
  </body>
</html>

app/views/lists/new.html.erb
<center>
<h1>New event</h1>
<table>
<%= form_for @event, :url => {:action => 'create'} do |f| %>
    <tr>
    <td><div>Title:</div></td>
    <td><div>
    <%= f.text_field :title %>
    </div>
    <% if @event.errors.messages[:title].any? %>
        <span style="color:red">
        <%= @event.errors.messages[:title][0] %>
        </span>
    <% end %>
    </td>
    </tr>
    <tr>
    <td><div>When:</div></td>
    <td><div><%= f.datetime_select :when %></div>
    <% if @event.errors.messages[:when].any? %>
        <span style="color:red">
        <%= @event.errors.messages[:when][0] %>
        </span>
    <% end %>
    </td>
    </tr>
    <tr>
    <td><div>Where:</div></td>
    <td><div><%= f.text_field :where %></div></td>
    </tr>
    <tr><td>What:</td>
    <td><div><%= f.text_field :what %></div>
    <% if @event.errors.messages[:what].any? %>
        <span style="color:red">
        <%= @event.errors.messages[:what][0] %>
        </span>
    <% end %>
    </td>
    </tr>
<tr>
<td><%= f.submit %></td>
</tr>
</table>
<% end %>
</center>
  

app/views/lists/show.html.erb
<head>
  <style>
    table td {
      padding: 30px;
      border: 1px solid rgb(20,24,24);
    }
    table td p {
      font-size: 2.0rem;

    }
    table td h2 {
      font-size: 3.8rem;
    }

  </style>
</head>

<h1><%= @event.title %>
<%= link_to "Join", "show_detail_path(show_detail)" %></h1>
<h2>ORGANIZERS</h2>
<table>
<tr>
<td>
<h2>WHAT?</h2>
<p><%= @event.what %></p>
</td>
<td>
<h2>WHEN?</h2>
<p><%= @event.when %></p>
</td>
<td>
<h2>WHERE?</h2>
<p><%= simple_format @event.where %></p>
</td>
</tr>
</table>
<% if !(@attendee.empty?) then %>
<h2>ALL MEMBERS</h2>
<% @attendee.each do |a| %>
<li>
<p><%= simple_format a.name %></p>
</li>
<% end %>
<% end %>

<script src="https://api.mqcdn.com/sdk/mapquest-js/v1.1.0/mapquest.js"></script>
<link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-js/v1.1.0/mapquest.css"/>
<script type="text/javascript">
    var place = gon.place
  window.onload = function() {
    L.mapquest.key = 'UShjaMayAC4UkuBJ5nu5rqFuraxzEOQU';

    var map = L.mapquest.map('map', {
      center: [0, 0],
      layers: L.mapquest.tileLayer('map'),
      zoom: 14
    });

    L.mapquest.geocoding().geocode(place);
  }
    if (window.name != "test") {
        location.reload();
        window.name = "test";
    } else {
        window.name = "";
　   }
</script>
<div id="map" style="width: 80%; height: 530px;"></div>

app/views/search/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script
  </head>

  <body style="overflow: scroll";>
  <h1>Search#index</h1>
  <p>Find me in app/views/search/index.html.erb</p>

  <div class="container">
    <% @events.each do |event| %>
    <div class="card" style="width: 20rem; float: left; margin: 30px 8px 20px 8px; border-radius: 2px; padding: 5px";>
      <% if event.image? %>
        <%= image_tag event.image, :class => "card-img-top" %>
      <% else %>
      <% end %>
      <div class="card-block">
        <h4 class="card-title"><%= event.title %><hr></h4>
        <p class="card-text"><%= event.what %></p>
        <p class="card-text"><%= event.where %></p>
        <p class="card-text"><%= event.when %></p>
        <%= link_to "Go somewhere", event_path(event), :class => "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </body>
</html>